change to local coverage combine and pytest-xdist (#871)
* change to local coverage combine and pytest-xdist

various improvements

* review feedback

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,7 +6,10 @@ on:
       - main
       - '*.x'
     tags:
-      - '*'
+      - "*"
+
+permissions:
+  contents: read
 
 jobs:
   linux:
@@ -15,9 +18,9 @@ jobs:
       fail-fast: false
       matrix:
         PYTHON:
-          - {VERSION: "3.12", NOXSESSION: "docs", COVERAGE: "false"}
-          - {VERSION: "3.12", NOXSESSION: "meta", COVERAGE: "false"}
-          - {VERSION: "3.12", NOXSESSION: "mypy", COVERAGE: "false"}
+          - {VERSION: "3.12", NOXSESSION: "docs"}
+          - {VERSION: "3.12", NOXSESSION: "meta"}
+          - {VERSION: "3.12", NOXSESSION: "mypy"}
           - {VERSION: "pypy-3.9", NOXSESSION: "tests"}
           - {VERSION: "pypy-3.10", NOXSESSION: "tests"}
           - {VERSION: "3.7", NOXSESSION: "tests"}
@@ -36,8 +39,8 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.PYTHON.VERSION }}
-      - name: Install nox and coverage
-        run: pip install nox coverage
+      - name: Install nox
+        run: pip install nox
       - name: Install libsodium (system install only)
         run: |
           wget --timeout=60 https://download.libsodium.org/libsodium/releases/LATEST.tar.gz || \
@@ -57,11 +60,7 @@ jobs:
         env:
           SODIUM_INSTALL_MINIMAL: ${{ matrix.PYTHON.SODIUM_INSTALL_MINIMAL }}
           SODIUM_INSTALL: ${{ matrix.PYTHON.SODIUM_INSTALL }}
-      - name: Upload coverage
-        run: |
-          curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash
-          bash codecov.sh -n "Python ${{ matrix.PYTHON.VERSION }}${{ matrix.PYTHON.NOTE }} on Linux"
-        if: matrix.PYTHON.COVERAGE != 'false'
+      - uses: ./.github/actions/upload-coverage
 
   macos:
     runs-on: ${{ matrix.RUNNER }}
@@ -84,16 +83,13 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.PYTHON.VERSION }}
-      - name: Install nox and coverage
-        run: pip install nox coverage
+      - name: Install nox
+        run: pip install nox
       - name: Run tests
         run: LIBSODIUM_MAKE_ARGS="-j$(sysctl -n hw.ncpu)" nox -s ${{ matrix.python.NOXSESSION }}
         env:
           SODIUM_INSTALL_MINIMAL: ${{ matrix.PYTHON.SODIUM_INSTALL_MINIMAL }}
-      - name: Upload coverage
-        run: |
-          curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash
-          bash codecov.sh -n "Python ${{ matrix.PYTHON.VERSION }}${{ matrix.PYTHON.NOTE }} on macOS"
+      - uses: ./.github/actions/upload-coverage
   windows:
     runs-on: ${{ matrix.WINDOWS.IMAGE }}
     strategy:
@@ -128,8 +124,8 @@ jobs:
         run: |
           Expand-Archive src/libsodium-1.0.20-stable-msvc.zip -DestinationPath c:\
         shell: powershell
-      - name: Install nox and coverage
-        run: pip install nox coverage
+      - name: Install nox
+        run: pip install nox
       - name: Run tests
         run: |
             call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=${{ matrix.WINDOWS.ARCH }}
@@ -141,7 +137,56 @@ jobs:
             nox -s ${{ matrix.PYTHON.NOXSESSION }}
             IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%
         shell: cmd
-      - name: Upload coverage
+      - uses: ./.github/actions/upload-coverage
+
+  all-green:
+    runs-on: ubuntu-latest
+    needs: [linux, macos, windows]
+    if: ${{ always() }}
+    timeout-minutes: 3
+    steps:
+      - uses: actions/checkout@v4.2.2
+        timeout-minutes: 3
+        with:
+          persist-credentials: false
+      - name: Decide whether the needed jobs succeeded or failed
+        uses: re-actors/alls-green@v1.2.2
+        with:
+          jobs: ${{ toJSON(needs) }}
+      - name: Setup python
+        if: ${{ always() }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.13"
+        timeout-minutes: 3
+      - run: pip install coverage[toml]
+        if: ${{ always() }}
+      - name: Download coverage data
+        if: ${{ always() }}
+        uses: actions/download-artifact@v4.3.0
+        with:
+          pattern: coverage-data-*
+          merge-multiple: true
+      - name: Combine coverage and fail if it's <100%.
+        if: ${{ always() }}
+        id: combinecoverage
         run: |
-          curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash || curl -o codecov.sh -f https://codecov.io/bash
-          bash codecov.sh -n "Python ${{ matrix.PYTHON.VERSION }} on Windows ${{ matrix.WINDOWS.ARCH }}"
+          set +e
+          echo "## Coverage" >> $GITHUB_STEP_SUMMARY
+          coverage combine
+          coverage report -m --fail-under 100
+          COV_EXIT_CODE=$?
+          if [ $COV_EXIT_CODE -ne 0 ]; then
+            echo "🚨 Coverage failed. Under 100%" | tee -a $GITHUB_STEP_SUMMARY
+          fi
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          coverage report -m >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          exit $COV_EXIT_CODE
+      - name: Upload HTML report
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-html-report
+          path: htmlcov
+          if-no-files-found: ignore
+        if: ${{ failure() && steps.combinecoverage.outcome == 'failure' }}
